/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MUESTRA_H_RPCGEN
#define _MUESTRA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct registro {
	int dni;
	char *nombre;
};
typedef struct registro registro;

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_registro (XDR *, registro*);

#else /* K&R C */
extern bool_t xdr_registro ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MUESTRA_H_RPCGEN */
/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MUESTRA_H_RPCGEN
#define _MUESTRA_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>


struct registro {
	int dni;
	char *nombre;
};
typedef struct registro registro;
#ifdef __cplusplus
extern "C" bool_t xdr_registro(XDR *, registro*);
#elif __STDC__
extern  bool_t xdr_registro(XDR *, registro*);
#else /* Old Style C */
bool_t xdr_registro();
#endif /* Old Style C */


#endif /* !_MUESTRA_H_RPCGEN */
/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MUESTRA_H_RPCGEN
#define _MUESTRA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct registro {
	int dni;
	char *nombre;
};
typedef struct registro registro;

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_registro (XDR *, registro*);

#else /* K&R C */
extern bool_t xdr_registro ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MUESTRA_H_RPCGEN */
/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MUESTRA_H_RPCGEN
#define _MUESTRA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct registro {
	int dni;
};
typedef struct registro registro;

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_registro (XDR *, registro*);

#else /* K&R C */
extern bool_t xdr_registro ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MUESTRA_H_RPCGEN */
/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MUESTRA_H_RPCGEN
#define _MUESTRA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct registro {
	int dni;
	char *nombre;
};
typedef struct registro registro;

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_registro (XDR *, registro*);

#else /* K&R C */
extern bool_t xdr_registro ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MUESTRA_H_RPCGEN */
