/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "muestra.h"

bool_t
xdr_registro (XDR *xdrs, registro *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->dni))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->nombre, 20))
		 return FALSE;
	return TRUE;
}
